package com.chromia.cli.command.deployment.proposal.dataprovider

import com.chromia.cli.command.deployment.proposal.gtv.diff.GtvDiffFinder
import com.chromia.cli.command.deployment.proposal.pruneAutoGeneratedConfigFields
import com.chromia.directory1.proposal_blockchain.GetConfigurationProposalAtResult
import com.chromia.directory1.proposal_blockchain.getConfigurationProposalAt
import com.github.ajalt.clikt.core.CliktCommand
import net.postchain.client.core.PostchainClient
import net.postchain.common.types.RowId
import net.postchain.gtv.GtvDecoder
import net.postchain.gtv.GtvDictionary

class ConfigurationProposalAtDataProvider : ProposalDataProvider<GetConfigurationProposalAtResult> {

    override fun formatData(data: GetConfigurationProposalAtResult, cliktCommand: CliktCommand): Any {
        val currentConf = pruneAutoGeneratedConfigFields(GtvDecoder.decodeGtv(data.currentConf.data.data) as GtvDictionary)
        val newConf = GtvDecoder.decodeGtv(data.proposedConf.data.data) as GtvDictionary
        return "Enabled at height: ${data.proposedConf.height}\n\n${GtvDiffFinder.diff(currentConf, newConf).diff}"
    }

    override fun getData(client: PostchainClient, proposalId: RowId): GetConfigurationProposalAtResult? {
        return client.getConfigurationProposalAt(proposalId)
    }
}