package com.chromia.cli.command.deployment.proposal.dataprovider

import com.chromia.cli.command.deployment.proposal.gtv.diff.GtvDiffFinder
import com.chromia.cli.command.deployment.proposal.pruneAutoGeneratedConfigFields
import com.chromia.directory1.proposal_blockchain.GetProposedForcedConfigurationResult
import com.chromia.directory1.proposal_blockchain.getProposedForcedConfiguration
import com.github.ajalt.clikt.core.CliktCommand
import net.postchain.client.core.PostchainClient
import net.postchain.common.types.RowId
import net.postchain.gtv.GtvDecoder
import net.postchain.gtv.GtvDictionary

class ProposedForcedConfigurationDataProvider : ProposalDataProvider<GetProposedForcedConfigurationResult> {

    override fun formatData(data: GetProposedForcedConfigurationResult, cliktCommand: CliktCommand): Any {
        val currentConf = pruneAutoGeneratedConfigFields(GtvDecoder.decodeGtv(data.currentConf.data.data) as GtvDictionary)
        val newConf = GtvDecoder.decodeGtv(data.forcedConf.configData.data) as GtvDictionary
        return "Force at height: ${data.forcedConf.height}\n\n${GtvDiffFinder.diff(currentConf, newConf).diff}"
    }

    override fun getData(client: PostchainClient, proposalId: RowId): GetProposedForcedConfigurationResult? {
        return client.getProposedForcedConfiguration(proposalId)
    }
}