include:
  - project: chromaway/core-infra/gitlab-automation
    ref: 1.3.3
    file:
      - templates/release.yml
      - templates/report-code-coverage.yml
      - templates/maven-dependency-scanning.yml
      - templates/container-dependency-scanning.yml

image: registry.gitlab.com/chromaway/core-tools/chromia-images/maven-docker-java21:1.0.11@sha256:a985644b469b4d01dcbd726176d69e238d8c7012c077a429beb65f86905d0bd1

.setup:
  artifacts:
    when: always
    paths:
      - "**/*.log"
      - $JACOCO_REPORT_DIR/*
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    expire_in: 1 week

stages:
  - build
  - code-coverage
  - deploy
  - dependency-check
  - release

build:
  extends:
    - .setup
    - .visualise-test-coverage
  stage: build
  interruptible: true
  except:
    refs:
      - tags
  script:
    - apt-get update
    - apt-get -y install ssh
    - mvn
      $MAVEN_CLI_OPTS
      --activate-profiles ci,docker,coverage
      clean verify

dependency-check:
  extends: .maven-dependency-check
  stage: dependency-check
  interruptible: true
  rules:
    - if: $RUN_DEPENDENCY_CHECK == "true"

container-scanning:
  variables:
    REGISTRY: registry.gitlab.com/chromaway/core-tools/chromia-cli
  parallel:
    matrix:
      - IMAGE: [ chr ]
        VERSION: [ latest ]
  only:
    variables:
      - $RUN_DEPENDENCY_CHECK == "true"

test-coverage-report:
  stage: code-coverage
  except:
    refs:
      - tags
  dependencies:
    - build

# Triggered by that a semver tag was pushed
deploy:
  extends: .setup
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - apt-get update
    - apt-get -y install ssh
    - mvn
      $MAVEN_CLI_OPTS
      --activate-profiles ci,docker,docker-push
      -Drevision=$CI_COMMIT_TAG
      clean source:jar deploy

trigger-homebrew-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    VERSION: $CI_COMMIT_TAG
    FORMULA: chr
  trigger:
    project: chromaway/core-tools/homebrew-chromia
    strategy: depend

trigger-scoop-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    VERSION: $CI_COMMIT_TAG
    APP: chr
  trigger:
    project: chromaway/core-tools/scoop-chromia
    strategy: depend

trigger-apt-repo-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    VERSION: $CI_COMMIT_TAG
    TOOL: chr
  script: |
    curl -L \
      --user "$JENKINS_USER:$JENKINS_USER_TOKEN" \
      --form TOOL=$TOOL \
      --form VERSION=$VERSION \
      --request POST \
      https://jenkins.infra.chromia.dev/job/apt-repository-chromia/buildWithParameters?token=$JENKINS_APT_JOB_TOKEN

update-docs:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    VERSION: $CI_COMMIT_TAG
  before_script:
    - !reference [ .git-setup, script ]
  script: |
    GIT_EMAIL=`git config user.email`
    GIT_NAME=`git config user.name`

    git clone https://x-token-auth:$BITBUCKET_CI_TOKEN@bitbucket.org/chromawallet/chromia-docs.git docs-repo
    cd docs-repo
    bash generate-chromia-cli-docs.sh
    bash generate-rell-docs.sh
    bash chromia-cli-release-notes.sh ../CHANGELOG.md docs/build/cli/cli-release-notes.mdx
    
    # Check if there are changes
    if [ `git status --porcelain | wc -l` -gt 0 ]; then
        # Commit and push the changes
        branch=chr-version-$VERSION

        git config user.email $GIT_EMAIL
        git config user.name $GIT_NAME

        git checkout -b $branch
        git add .
        git commit -m "Update chromia-cli docs to version $VERSION"
        git push origin $branch

        # Create a merge request
        curl -v --request POST \
            --header 'Authorization: Bearer '"$BITBUCKET_CI_TOKEN" \
            --header 'Accept: application/json' \
            --header "Content-Type: application/json" \
            --data '{
                "title": "BUILD_USER: Update chromia cli docs version '"$VERSION"'", 
                "source": {"branch": {"name": "'"$branch"'"}},
                "destination": {"branch": {"name": "master"}}
            }' \
            "https://api.bitbucket.org/2.0/repositories/chromawallet/chromia-docs/pullrequests"
      else
        echo "No changes to commit."
      fi

gitlab-release:
  extends: .gitlab-release-with-notes
  script:
    - echo "Release CHR $CI_COMMIT_TAG"
  release:
    name: 'CHR $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Build Artifact (.tar.gz)'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/com/chromia/cli/chromia-cli/${CI_COMMIT_TAG}/chromia-cli-${CI_COMMIT_TAG}-dist.tar.gz'
          link_type: 'package'
        - name: 'Build Artifact (.zip)'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven/com/chromia/cli/chromia-cli/${CI_COMMIT_TAG}/chromia-cli-${CI_COMMIT_TAG}-dist.zip'
          link_type: 'package'

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s .gitlab-settings.xml"
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  DOCKER_HOST: tcp://docker:2375
  POSTGRES_DB: postchain
  POSTGRES_USER: postchain
  POSTGRES_PASSWORD: postchain
  POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain
  CHR_DB_URL: jdbc:postgresql://postgres/postchain
  JACOCO_REPORT_DIR: coverage-report-aggregate/target/site/jacoco-aggregate

services:
  - postgres:14.9-alpine3.18
  - name: docker:20-dind
    alias: docker
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" , "--experimental" ]
# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
