blockchains:
  My_Rell_Project:
    module: main
  My_Rell_Project2:
    module: main2
    blockchainStrategy:
      maxblocktime: 2000

#TODO add anchoring for blockchainStrategy

deployment:
  test:
    brid: AB12332345677234234234234234234234333324234234234234232311133135
    apiUrl: http://localhost:7740
    containerName: joar
  devnet:
    brid: CDEF332345677234234234234234234234333324234234234234232311133135
    licence: lnaalnd4523-3= (container id)
    apiUrl: http://192.0.0.1:7740
    containerName: calle

compile:
  gtv: false
  deprecatedError: true
  ide: false
  blockCheck: false
  testLib: false
  hiddenLib: false
  allowDbModificationsInObjectExprs: false
  rellVersion: 0.10.10
  symbolInfoFile: null
  quiet: false

database:
  password: postchain
  username: postchain
  database: postchain
  host: localhost