#!/bin/bash

set -eu

app_path=$0

while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit

JAR=$(find "$APP_HOME/lib" -maxdepth 1 -type f -print | grep -E '/chromia-cli-(dev|[0-9]+\.[0-9]+\.[0-9]+)\.jar$')
RESOLVED_TMP_DIR=${TMPDIR-/tmp}
LOG_FOLDER="${RESOLVED_TMP_DIR%/}/chromia"

exec ${RELL_JAVA:-java} -DCHR_LOG_FOLDER="$LOG_FOLDER" -cp "$JAR:$APP_HOME/lib/*" com.chromia.MainKt "$@"
