CompilerOptions:
  gtv: false
  deprecatedError: true
  ide: false
  blockCheck: false
  testLib: false
  hiddenLib: false
  allowDbModificationsInObjectExprs: false
  rellVersion: 0.10.10
  symbolInfoFile: null