<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia.cli</groupId>
        <artifactId>chromia-cli-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>chromia-cli</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>Chromia Cli</name>

    <properties>
        <revision>dev</revision>
        <directory.source>${project.build.directory}/directory-chain/src</directory.source>

        <assembly.path>${project.basedir}/src/main/assembly/targz.xml</assembly.path>

        <image.name>chr</image.name>
        <main.class>com.chromia.MainKt</main.class>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <configuration>
                    <source>${directory.source}</source>
                </configuration>
                <executions>
                    <execution>
                        <id>rell-client-gen</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>com.chromia.directory1</packageName>
                            <mainModule>version,proposal_blockchain</mainModule>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-archive</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${assembly.path}</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
            </plugin>

        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <configuration>
                        <allowInsecureRegistries>false</allowInsecureRegistries>
                        <from>
                            <image>
                                registry.gitlab.com/chromaway/core-tools/chromia-images/java17:1.0.2@sha256:756673c4f33a67b88dbc4ce0019137b13e9bd351cee804cfbbda3b9aa9a2cba2
                            </image>
                        </from>
                        <container>
                            <entrypoint>
                                <args>/usr/bin/chr-entrypoint.sh</args>
                            </entrypoint>
                            <args>
                                <arg>chr</arg>
                            </args>
                            <appRoot>/usr/share/chr</appRoot>
                            <workingDirectory>/usr/app</workingDirectory>
                            <mainClass>${main.class}</mainClass>
                            <creationTime>${git.commit.time}</creationTime>
                            <filesModificationTime>${git.commit.time}</filesModificationTime>
                        </container>
                        <extraDirectories>
                            <permissions>
                                <permission>
                                    <file>/usr/bin/chr</file>
                                    <mode>755</mode>
                                </permission>
                                <permission>
                                    <file>/usr/bin/chr-entrypoint.sh</file>
                                    <mode>755</mode>
                                </permission>
                            </permissions>
                        </extraDirectories>
                        <containerizingMode>packaged</containerizingMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>docker-build</id>
                            <phase>package</phase>
                            <goals>
                                <goal>dockerBuild</goal>
                            </goals>
                            <configuration>
                                <to>
                                    <image>${image.name}</image>
                                </to>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.chromia.cli</groupId>
            <artifactId>chromia-build-tools</artifactId>
        </dependency>
        <dependency>
            <groupId>com.chromia.cli</groupId>
            <artifactId>chromia-build-tools</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.chromia.cli</groupId>
            <artifactId>chromia-cli-tools</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-gtx</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-shell</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-base</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>postchain-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-base</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>codegen-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>codegen-typescript</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>codegen-javascript</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-core</artifactId>
            <version>${eif.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.ajalt.clikt</groupId>
            <artifactId>clikt-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.http4k</groupId>
            <artifactId>http4k-core</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.forkhandles</groupId>
            <artifactId>result4k</artifactId>
        </dependency>
        <dependency>
            <groupId>org.http4k</groupId>
            <artifactId>http4k-format-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-devtools</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.org.webcompere</groupId>
            <artifactId>system-stubs-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.redundent</groupId>
            <artifactId>kotlin-xml-builder</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.bitcoinj</groupId>
            <artifactId>bitcoinj-core</artifactId>
            <version>0.16.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15to18</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-javalite</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>artifact</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>!local</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-scm-plugin</artifactId>
                        <version>1.11.2</version>
                        <executions>
                            <execution>
                                <id>d1-resources</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://gitlab.com/chromaway/core/directory-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/directory-chain</checkoutDirectory>
                                    <scmVersion>${directory.chain.version}</scmVersion>
                                    <scmVersionType>tag</scmVersionType>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <directory.source>${project.basedir}/../../directory-chain/src</directory.source>
            </properties>
        </profile>
        <profile>
            <id>docker</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>docker-arm</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-build</id>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <os>linux</os>
                                                    <architecture>arm64</architecture>
                                                </platform>
                                            </platforms>
                                        </from>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>docker-push</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-push</id>
                                    <phase>deploy</phase>
                                    <goals>
                                        <goal>build</goal>
                                    </goals>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <architecture>amd64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                                <platform>
                                                    <architecture>arm64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                            </platforms>
                                        </from>
                                        <to>
                                            <image>${gitlab.registry}/${image.name}:${project.version}</image>
                                            <auth>
                                                <username>${env.CI_REGISTRY_USER}</username>
                                                <password>${env.CI_REGISTRY_PASSWORD}</password>
                                            </auth>
                                        </to>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>
