package com.chromia.cli.command.deployment.proposal

import net.postchain.gtv.GtvDictionary
import net.postchain.gtv.GtvFactory

fun pruneAutoGeneratedConfigFields(config: GtvDictionary): GtvDictionary =
        GtvFactory.gtv(config.asDict().filterKeys { !AUTO_GENERATED_CONFIG_FIELDS.contains(it) })

val AUTO_GENERATED_CONFIG_FIELDS = setOf(
        "chain0_last_block_rid",
        "chain0_block_height",
        "chain0_tx_rid",
        "chain0_op_index"
)

fun formatThreshold(threshold: Long): String {
    return when (threshold) {
        0L -> "super majority (>66.66%)"
        -1L -> "majority (>50%)"
        else -> threshold.toString()
    }
}