#!/usr/bin/env zsh
# Command completion for no-op-clikt
# Generated by Clikt

autoload bashcompinit
bashcompinit

__skip_opt_eq() {
    # this takes advantage of the fact that bash functions can write to local
    # variables in their callers
    (( i = i + 1 ))
    if [[ "${COMP_WORDS[$i]}" == '=' ]]; then
          (( i = i + 1 ))
    fi
}

_no_op_clikt() {
  local i=1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        --generate-completion)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--generate-completion' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      test)
        _no_op_clikt_test $(( i + 1 ))
        return
        ;;
      repl)
        _no_op_clikt_repl $(( i + 1 ))
        return
        ;;
      start)
        _no_op_clikt_start $(( i + 1 ))
        return
        ;;
      deploy)
        _no_op_clikt_deploy $(( i + 1 ))
        return
        ;;
      compile)
        _no_op_clikt_compile $(( i + 1 ))
        return
        ;;
      query)
        _no_op_clikt_query $(( i + 1 ))
        return
        ;;
      tx)
        _no_op_clikt_tx $(( i + 1 ))
        return
        ;;
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '--generate-completion -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --generate-completion)
      ;;
    --help)
      ;;
    *)
      COMPREPLY=($(compgen -W 'test repl start deploy compile query tx' -- "${word}"))
      ;;
  esac
}

_no_op_clikt_test() {
  local i=$1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -d|--source-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--source-dir' || in_param=''
          continue
          ;;
        -m|--modules)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--modules' || in_param=''
          continue
          ;;
        -brid|--blockchain-rid)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain-rid' || in_param=''
          continue
          ;;
        -db|--database|--no-db)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -cid|--chainid)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--chainid' || in_param=''
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-d --source-dir -m --modules -brid --blockchain-rid -db --database --no-db -cid --chainid -s --settings -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --source-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --modules)
      ;;
    --blockchain-rid)
      ;;
    --database)
      ;;
    --chainid)
      ;;
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --help)
      ;;
  esac
}

_no_op_clikt_repl() {
  local i=$1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        -cid|--chainid)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--chainid' || in_param=''
          continue
          ;;
        --wipe)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -d|--source-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--source-dir' || in_param=''
          continue
          ;;
        -db|--database|--no-db)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -e|--entry)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--entry' || in_param=''
          continue
          ;;
        -m|--module)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--module' || in_param=''
          continue
          ;;
        -a|--args)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--args' || in_param=''
          continue
          ;;
        --json)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-s --settings -cid --chainid --wipe -d --source-dir -db --database --no-db -e --entry -m --module -a --args --json -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --chainid)
      ;;
    --wipe)
      ;;
    --source-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --database)
      ;;
    --entry)
      ;;
    --module)
      ;;
    --args)
      ;;
    --json)
      ;;
    --help)
      ;;
  esac
}

_no_op_clikt_start() {
  local i=$1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -d|--source-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--source-dir' || in_param=''
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        -np|--node-properties)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--node-properties' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-d --source-dir -s --settings -np --node-properties -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --source-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --node-properties)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --help)
      ;;
  esac
}

_no_op_clikt_deploy() {
  local i=$1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -o|--output-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--output-dir' || in_param=''
          continue
          ;;
        --show-brid)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -d|--source-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--source-dir' || in_param=''
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        --target)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--target' || in_param=''
          continue
          ;;
        --blockchain)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain' || in_param=''
          continue
          ;;
        --secret)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--secret' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-o --output-dir --show-brid -d --source-dir -s --settings --target --blockchain --secret -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --output-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --show-brid)
      ;;
    --source-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --target)
      ;;
    --blockchain)
      ;;
    --secret)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --help)
      ;;
  esac
}

_no_op_clikt_compile() {
  local i=$1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -d|--source-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--source-dir' || in_param=''
          continue
          ;;
        -o|--output-dir)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--output-dir' || in_param=''
          continue
          ;;
        --show-brid)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-d --source-dir -o --output-dir --show-brid -s --settings -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --source-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --output-dir)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --show-brid)
      ;;
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --help)
      ;;
  esac
}

_no_op_clikt_query() {
  local i=$1
  local in_param=''
  local fixed_arg_names=('QUERYNAME')
  local vararg_name='ARGS'
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        --secret)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--secret' || in_param=''
          continue
          ;;
        --deployment|--local)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        --name)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--name' || in_param=''
          continue
          ;;
        --blockchain)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain' || in_param=''
          continue
          ;;
        --blockchain-rid)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain-rid' || in_param=''
          continue
          ;;
        --api-url)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--api-url' || in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-s --settings --secret --deployment --local --name --blockchain --blockchain-rid --api-url -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --secret)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --deployment)
      ;;
    --name)
      ;;
    --blockchain)
      ;;
    --blockchain-rid)
      ;;
    --api-url)
      ;;
    --help)
      ;;
    QUERYNAME)
      ;;
    ARGS)
      ;;
  esac
}

_no_op_clikt_tx() {
  local i=$1
  local in_param=''
  local fixed_arg_names=('OPNAME')
  local vararg_name='ARGS'
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -s|--settings)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--settings' || in_param=''
          continue
          ;;
        --secret)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--secret' || in_param=''
          continue
          ;;
        --deployment|--local)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        --name)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--name' || in_param=''
          continue
          ;;
        --blockchain)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain' || in_param=''
          continue
          ;;
        --blockchain-rid)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--blockchain-rid' || in_param=''
          continue
          ;;
        --api-url)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--api-url' || in_param=''
          continue
          ;;
        --await|-a)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -nop)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-s --settings --secret --deployment --local --name --blockchain --blockchain-rid --api-url --await -a -nop -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --settings)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --secret)
       COMPREPLY=($(compgen -o default -- "${word}"))
      ;;
    --deployment)
      ;;
    --name)
      ;;
    --blockchain)
      ;;
    --blockchain-rid)
      ;;
    --api-url)
      ;;
    --await)
      ;;
    -nop)
      ;;
    --help)
      ;;
    OPNAME)
      ;;
    ARGS)
      ;;
  esac
}

complete -F _no_op_clikt no-op-clikt
